#!/bin/bash

# Ensure required parameters are provided
if [ -z "$1" ] || [ -z "$2" ]; then
    echo "Usage: $0 <message_prompt> <command>"
    exit 1
fi

MESSAGE_PROMPT="$1"
COMMAND_TO_RUN="$2"

ACTION=$(dunstify \
                 -A confirm,Confirm_YES \
                 -r 9999 \
                 "$MESSAGE_PROMPT" \
                 "Mod+Y/Mod+N" | grep -oE 'confirm')

if [ "$ACTION" = "confirm" ]; then
    eval "$COMMAND_TO_RUN"
fi
